### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by livxy** [timof121/timof121#2]
can u send me the source code for this button on:
[https://www.yourjs.com/bookmarklet/](https://www.yourjs.com/bookmarklet/
)
![image](https://user-images.githubusercontent.com/67598470/199250771-1e9302a4-1474-4983-b38f-b94134a8cf82.png)

I'm on a school Chromebook and inspect element & source code are blocked 👎 
I want to learn how to convert js code to a bookmarklet using google closure compiler

**Comment by timof121** [comment]
LOL

**Comment by livxy** [comment]
why did i make this :sob:

**Comment by livxy** [comment]
how do i delete issue
